### ISSUE TITLE
[REQUEST TEXT]Siwasi's tafsir

### ISSUE THREAD

**Issue by s-ross** [OpenITI/barzakh#8]
Dear Open ITI,

First, a huge thanks for your amazing contribution to the field! OpenITI is extraordinary.

I was wondering if it would be possible to create a digital edition (removing footnotes) of the following text?

It is one of the top-50 most longitudinally popular tafsirs according to my research (article in progress):
https://www.youtube.com/watch?v=uZbWDM5O3B4

Thank you!

Sincerely,

-Samuel Ross
s.ross@tcu.edu
Texas Chrisitan University

***
Ahmad ibn Muhammad al-Siwasi
'Uyun al-Tafasir li-l-fudala' al-samamir
The book was recently published and added to the Shamela:
http://almeshkat.net/book/14977

**Comment by pverkind** [comment]
Added to barzakh as 0860AhmadSiwasi.CuyunTafasir.Meshkat00042488-ara1

**Comment by pverkind** [comment]
Added to the corpus
