### ISSUE TITLE
[REQUEST TEXT] Sulayman al-Jamal's tafsir

### ISSUE THREAD

**Issue by s-ross** [OpenITI/barzakh#9]
Dear Open ITI,

First, a huge thanks for your amazing contribution to the field! OpenITI is extraordinary.

I was wondering if it would be possible to create a digital edition (removing footnotes) of the following text?

It is one of the top-50 most longitudinally popular tafsirs according to my research (article in progress):
https://www.youtube.com/watch?v=uZbWDM5O3B4

Thank you!

Sincerely,

-Samuel Ross
s.ross@tcu.edu
Texas Chrisitan University

Sulayman al-Jamal
Hashiyat al-Jamal ala Tafsir al-Jalalayn

The book was recently published but does not seem to be available in Shamela .BOK format yet, only as a PDF:
https://ia802802.us.archive.org/17/items/0_20200111/0%D9%85%D9%84%D9%81%20%D9%88%D8%A7%D8%AD%D8%AF.pdf

**Comment by pverkind** [comment]
Dear Samuel, we OCR'ed the text but the result is not great; the OCR did not pick up on the division of the page that splits the main text from the commentary. See https://github.com/OpenITI/Annotation/issues/2839
We'll see if we can improve this by training the model in recognizing this type of division.

**Comment by pverkind** [comment]
Added to the corpus
